
trigger:
  branches:
    include:
    - '*'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: Node Installation
  displayName: 'Node Installation'
  jobs:
  - job: Node Installation
    displayName: 'Node Installation'
    pool:
      vmImage: 'ubuntu-latest'
    - task: NodeTool@0
	  inputs:
		versionSpec: '10.x'
	  displayName: 'Install Node.js'
    - script: echo provisioning to feature environment
      displayName: 'Feature environment provisioning'
