# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - '*'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: node_module_installation
  displayName: 'Node Module Installation'
  jobs:
  - job: node_module_installation
    displayName: 'node_module_installation'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
	- task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
    - script: npm install
      displayName: 'node_module_installation'

- stage: provision_to_develop_env
  displayName: 'Provision resources to develop environment'
  jobs:
  - job: develop_provisioning
    displayName: 'Develop env provisioning job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo provisioning to develop environment
      displayName: 'Develop environment provisioning'

- stage: provision_to_production_env
  displayName: 'Provision resources to production environment'
  jobs:
  - job: production_provisioning
    displayName: 'Prodduction env provisioning job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo provisioning to production environment
      displayName: 'production environment provisioning'
