trigger:
  branches:
    include:
    - '*'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: Node Installation
  displayName: 'Node Installation'
  jobs:
  - job: Node Installation
    displayName: 'Node Installation'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
         npm install
         npm run build
    displayName: 'npm install and build'



