stages:
- stage: Package Installation
  pool:
      vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          displayName: 'Install Node.js'
  - script: |
    npm install
    displayName: 'npm install'
	
- stage: Build
  steps: 
  - script: |
  'npm run build'
  displayName: 'npm run build'
