
trigger:
  branches:
    include:
    - '*'

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

stages:
- stage: provision_to_feature_env
  displayName: 'Provision resources to feature environment'
  jobs:
  - job: feature_provisioning
    displayName: 'Feature env provisioning job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo provisioning to feature environment
      displayName: 'Feature environment provisioning'
